/**
 * Model Router — Runtime model selection using the auto-generated manifest.
 *
 * At runtime, reads lib/ai/model-manifest.json (generated by scripts/evaluate-models.ts).
 * Falls back to safe defaults if the manifest is missing (e.g. first deploy).
 *
 * The manifest is regenerated:
 *   - Every 2 weeks via GitHub Actions
 *   - When new models are released (workflow_dispatch)
 *   - When new BidBlender tasks are added (push to lib/ai/constants.ts or types.ts)
 *   - Manually: npx tsx scripts/evaluate-models.ts
 */

import type { ModelProfile, Paradigm } from "./types";

// ────────────────────────────────────────────────────────────────────
// Manifest types (mirrors packages/mcp-model-router/src/discover.ts)
// ────────────────────────────────────────────────────────────────────

interface ManifestAllocation {
  taskId: string;
  allocatedModel: string;
  fallbackModel: string;
  estimatedCostPer1kTokens: number;
  complexity: "low" | "medium" | "high";
  requiresReasoning: boolean;
}

interface AllocationManifest {
  generatedAt: string;
  nextEvaluationAt: string;
  allocations: Record<string, ManifestAllocation>;
  summary: {
    allocatedModels: string[];
  };
}

// ────────────────────────────────────────────────────────────────────
// Hardened fallback table
//
// Used when no manifest exists (first deploy, CI, etc.)
// Maps paradigm → { economy, balanced, deep }
// ────────────────────────────────────────────────────────────────────

const FALLBACK_ALLOCATION: Record<Paradigm, { economy: string; balanced: string; deep: string }> = {
  LOW_COST_EXTRACTION:            { economy: "gpt-4o-mini",  balanced: "gpt-4o-mini",  deep: "gpt-4.1-mini" },
  OPPORTUNITY_INTELLIGENCE:       { economy: "gpt-4o-mini",  balanced: "gpt-4.1",      deep: "gpt-5.4"      },
  COMPANY_FIT:                    { economy: "gpt-4.1-mini", balanced: "gpt-4.1",      deep: "gpt-5.4"      },
  NETWORK_INFLUENCE:              { economy: "gpt-4o-mini",  balanced: "gpt-4.1",      deep: "gpt-5.4"      },
  COMPETITIVE_LANDSCAPE:          { economy: "gpt-4.1-mini", balanced: "gpt-5.4-mini", deep: "gpt-5.4"      },
  STRATEGIC_BID_INTELLIGENCE:     { economy: "gpt-5.4-mini", balanced: "gpt-5.4",      deep: "gpt-5.4-pro"  },
  CROSS_OPPORTUNITY_INTELLIGENCE: { economy: "gpt-5.4-mini", balanced: "gpt-5.4",      deep: "gpt-5.4-pro"  },
  ADDENDA_CHANGE_ANALYSIS:        { economy: "gpt-4.1-mini", balanced: "gpt-5.4-mini", deep: "gpt-5.4"      },
  KNOWLEDGE_BASE_INTELLIGENCE:    { economy: "gpt-4o-mini",  balanced: "gpt-4.1-mini", deep: "gpt-4.1"      },
};

// ────────────────────────────────────────────────────────────────────
// Known reasoning models (need reasoning_effort, not temperature)
// ────────────────────────────────────────────────────────────────────

const REASONING_MODEL_PREFIXES = ["o1", "o3", "o4", "o5"];

function isReasoningModel(modelId: string): boolean {
  return REASONING_MODEL_PREFIXES.some((prefix) =>
    modelId === prefix ||
    modelId.startsWith(`${prefix}-`) ||
    modelId.startsWith(`${prefix}-mini`) ||
    modelId.startsWith(`${prefix}-pro`)
  );
}

// ────────────────────────────────────────────────────────────────────
// Manifest loader (lazy, cached per process lifetime)
// ────────────────────────────────────────────────────────────────────

let _manifest: AllocationManifest | null | "unloaded" = "unloaded";

function loadManifest(): AllocationManifest | null {
  if (_manifest !== "unloaded") return _manifest;

  try {
    // Dynamic require so this works in both CJS and ESM/Next.js bundles
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const raw = require("./model-manifest.json") as AllocationManifest;
    _manifest = raw;

    const stale = new Date() >= new Date(raw.nextEvaluationAt);
    if (stale) {
      console.warn(
        "[model-router] ⚠️  model-manifest.json is past its evaluation date. " +
        "Run `npx tsx scripts/evaluate-models.ts --scheduled` or let GitHub Actions refresh it."
      );
    }

    return _manifest;
  } catch {
    _manifest = null;
    console.warn(
      "[model-router] ⚠️  No model-manifest.json found. Using fallback allocations. " +
      "Run `npx tsx scripts/evaluate-models.ts` to generate the manifest."
    );
    return null;
  }
}

// ────────────────────────────────────────────────────────────────────
// Public API
// ────────────────────────────────────────────────────────────────────

export interface ModelSelection {
  modelId: string;
  reasoning: boolean;
  temperature: number;
  reasoningEffort?: "low" | "medium" | "high";
  /** Source of the selection: manifest | fallback | override */
  source: "manifest" | "fallback" | "override";
}

/**
 * Select the best model for a given analysis job.
 *
 * Priority:
 *   1. Explicit model override (env var or request field)
 *   2. Auto-generated manifest allocation
 *   3. Hardened fallback table
 */
export function selectModel(
  paradigm: Paradigm,
  modelProfile: ModelProfile,
  opts?: {
    modelOverride?: string | null;
  }
): ModelSelection {
  // 1. Explicit override
  const override = opts?.modelOverride ?? process.env.OPENAI_MODEL_OVERRIDE ?? null;
  if (override) {
    const reasoning = isReasoningModel(override);
    return {
      modelId: override,
      reasoning,
      temperature: reasoning ? 1 : 0.2,
      reasoningEffort: reasoning ? profileToReasoningEffort(modelProfile) : undefined,
      source: "override",
    };
  }

  // 2. Manifest allocation
  const manifest = loadManifest();
  if (manifest?.allocations[paradigm]) {
    const alloc = manifest.allocations[paradigm];
    const modelId = modelProfile === "economy"
      ? alloc.fallbackModel   // economy → prefer cheaper fallback
      : alloc.allocatedModel; // balanced/deep → use primary allocation
    const reasoning = isReasoningModel(modelId);
    return {
      modelId,
      reasoning,
      temperature: reasoning ? 1 : 0.2,
      reasoningEffort: reasoning ? profileToReasoningEffort(modelProfile) : undefined,
      source: "manifest",
    };
  }

  // 3. Fallback table
  const fallbackRow = FALLBACK_ALLOCATION[paradigm];
  const modelId = fallbackRow?.[modelProfile] ?? "gpt-4o-mini";
  const reasoning = isReasoningModel(modelId);
  return {
    modelId,
    reasoning,
    temperature: reasoning ? 1 : 0.2,
    reasoningEffort: reasoning ? profileToReasoningEffort(modelProfile) : undefined,
    source: "fallback",
  };
}

function profileToReasoningEffort(profile: ModelProfile): "low" | "medium" | "high" {
  return profile === "economy" ? "low" : profile === "balanced" ? "medium" : "high";
}

/**
 * Estimate cost using the manifest's known pricing, or a safe default.
 */
export function estimateModelCost(
  inputTokens: number,
  outputTokens: number,
  modelId: string
): number {
  // Cost rates from discover.ts KNOWN_MODELS — kept in sync via manifest evaluation
  const COST_HINT: Record<string, [number, number]> = {
    "gpt-5.4-pro":  [30.00, 180.00],
    "gpt-5.4":      [2.50,  15.00],
    "gpt-5.4-mini": [0.75,  4.50],
    "gpt-5.4-nano": [0.20,  1.25],
    "gpt-5-pro":    [15.00, 90.00],
    "gpt-5":        [2.00,  8.00],
    "gpt-5-mini":   [0.50,  3.00],
    "gpt-5-nano":   [0.10,  0.60],
    "gpt-4.1":      [2.00,  8.00],
    "gpt-4.1-mini": [0.40,  1.60],
    "gpt-4.1-nano": [0.10,  0.40],
    "gpt-4o":       [2.50,  10.00],
    "gpt-4o-mini":  [0.15,  0.60],
    "o3":           [2.00,  8.00],
    "o3-mini":      [1.10,  4.40],
    "o4-mini":      [1.10,  4.40],
    "o1":           [15.00, 60.00],
    "o1-pro":       [150.00, 600.00],
  };

  const key = Object.keys(COST_HINT).find((k) => modelId.includes(k));
  const [inPerM, outPerM] = key ? COST_HINT[key] : [0.15, 0.60];
  return (inputTokens / 1_000_000) * inPerM + (outputTokens / 1_000_000) * outPerM;
}

/** Invalidate the cached manifest (call after running evaluate-models) */
export function invalidateManifestCache() {
  _manifest = "unloaded";
}
