/**
 * Auto-generated by scripts/evaluate-models.ts.
 * Do not edit by hand.
 */

export const PARADIGM_MODEL_ALLOCATION = {
  LOW_COST_EXTRACTION: { primary: "gpt-5.4-nano", economy: "gpt-5-nano" },
  OPPORTUNITY_INTELLIGENCE: { primary: "gpt-5-mini", economy: "gpt-4.1-mini" },
  COMPANY_FIT: { primary: "gpt-5-mini", economy: "gpt-4.1-mini" },
  NETWORK_INFLUENCE: { primary: "gpt-5-mini", economy: "gpt-4.1-mini" },
  COMPETITIVE_LANDSCAPE: { primary: "gpt-5-mini", economy: "gpt-4.1-mini" },
  STRATEGIC_BID_INTELLIGENCE: { primary: "o3-mini", economy: "o4-mini" },
  CROSS_OPPORTUNITY_INTELLIGENCE: { primary: "o3-mini", economy: "o4-mini" },
  ADDENDA_CHANGE_ANALYSIS: { primary: "gpt-4.1-mini", economy: "gpt-4.1-mini" },
  KNOWLEDGE_BASE_INTELLIGENCE: { primary: "gpt-5.4-nano", economy: "gpt-5-nano" },
  DOCUMENT_ANALYSIS_CHAT: { primary: "gpt-4.1-mini", economy: "gpt-4.1-mini" },
} as const;
